version: "2.3"

networks:
  nominatim_external_network:
  nominatim_internal_network:
    internal: true

services:
  # https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build:
      context: ./test
      dockerfile: Dockerfile
    depends_on:
      nominatim-db:
        condition: service_started
      nominatim:
        condition: service_started
      nominatim-nginx:
        condition: service_started
    networks:
      - nominatim_internal_network
    volumes_from:
      - nominatim
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  nominatim:
    # For development or CI, tag build from local Dockerfile
    build:
      context: ./
      dockerfile: Dockerfile
      args: 
        - TAG=${TAG}
        - VCS_REF=${VCS_REF}
        - BUILD_DATE=${BUILD_DATE}
    image: monogramm/docker-nominatim:ci
    # For production, download prebuilt image
    #image: ${IMAGE_NAME}
    container_name: nominatim
    #restart: always
    depends_on:
      nominatim-db:
        condition: service_started
        #condition: service_healthy
    links:
      - nominatim-db
    expose:
      - '9000'
    #ports:
    #  - "9000:9000"
    networks:
      - nominatim_internal_network
    volumes:
      - $NOMINATIM_HOME/data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - GEOFABRIK_DOWNLOAD_URL=http://download.geofabrik.de/europe/monaco-latest.osm.pbf
      - GEOFABRIK_REPLICATION_URL=http://download.geofabrik.de/europe/monaco-updates
      # Wait 1 minute before checking DB
      - WAIT_STEP=60
      # Timeout after 1 day of waiting DB (init can be very long...)
      - WAIT_TIMEOUT=86400
      - NOMINATIM_DB_DRIVER=pgsql
      - NOMINATIM_DB_HOST=nominatim-db
      - NOMINATIM_DB_PORT=5432
      - NOMINATIM_DB_NAME=$NOMINATIM_DB_NAME
      - NOMINATIM_DB_USER=$NOMINATIM_DB_USER
      - NOMINATIM_DB_PASSWORD=$NOMINATIM_DB_PASSWD

  nominatim-db:
    image: monogramm/docker-nominatim:ci
    container_name: nominatim-db
    #restart: always
    expose:
      - '5432'
    #ports:
    #  - "5432:5432"
    #healthcheck:
    #  test: ["CMD", "pg_isready", "-U", "${NOMINATIM_DB_USER}", "-d", "${NOMINATIM_DB_NAME}"]
    networks:
      - nominatim_internal_network
    volumes:
      - $NOMINATIM_HOME/data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      #- NOMINATIM_INIT_THREADS=4
      - NOMINATIM_MAP_NAME=monaco-latest.osm.pbf
      - NOMINATIM_DB_PATH=monaco-latest-postgres
      - GEOFABRIK_DOWNLOAD_URL=http://download.geofabrik.de/europe/monaco-latest.osm.pbf

  nominatim-nginx:
    image: nginx:latest
    container_name: nominatim-nginx
    restart: always
    ports:
      - "80:80"
      # If you need SSL connection
      # - "443:443"
    networks:
      - nominatim_internal_network
      - nominatim_external_network
    depends_on:
      nominatim:
        condition: service_started
    links:
      - nominatim
    volumes:
      - $NOMINATIM_HOME/html:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # TODO Provide a custom nginx conf
      #- ./nginx.conf:/etc/nginx/nginx.conf:ro
      # If you need SSL connection, you can provide your own certificates
      # - ./certs:/etc/letsencrypt
      # - ./certs-data:/data/letsencrypt
    environment:
      - NGINX_HOST=localhost # set your local domain or your live domain
      # - NGINX_CGI=nominatim:9000 # same as nominatim container name
