os: linux
dist: xenial

services: docker

language: shell

branches:
  only:
    - main
    - master
    - develop

before_install:
  - env | sort
  - dir="images/${VERSION}/${VARIANT}"

install:
  - cd "$dir"
  # Execute CI build hooks
  - ./hooks/run build "${VARIANT}"

before_script:
  # Display docker images
  - docker images
  # FIXME Manually download OSM map
  #- sudo mkdir -p '/srv/nominatim/data/'
  #- sudo wget -O '/srv/nominatim/data/monaco-latest.osm.pbf' 'http://download.geofabrik.de/europe/monaco-latest.osm.pbf'

script:
  - cd "$dir"
  # Execute CI test hooks
  - ./hooks/run test "${VARIANT}"

notifications:
  email: false

jobs:
  allow_failures:
    - env: VERSION=2.5 VARIANT=debian
    - env: VERSION=3.0 VARIANT=debian
    - env: VERSION=3.1 VARIANT=debian
    - env: VERSION=3.2 VARIANT=debian
    - env: VERSION=3.3 VARIANT=debian

env: # Environments
    - VERSION=3.4 VARIANT=debian
    - VERSION=3.5 VARIANT=debian
    - VERSION=3.6 VARIANT=debian
    - VERSION=3.7 VARIANT=debian
